### ISSUE TITLE
Undefined Parameter type {actor}, Please register a Parameter Type for {actor} 

### ISSUE THREAD

**Issue by kpkalyan** [serenity-bdd/serenity-cucumber6#10]
ERROR:
========
Showing an error in Spring tool suite IDE console : "Undefined Parameter type {actor}, Please register a Parameter Type for {actor}" for each step definition files
image

ParameterDefinitions.java:
=======================
import io.cucumber.java.ParameterType;
import net.serenitybdd.screenplay.Actor;
import net.serenitybdd.screenplay.actors.OnStage;

public class ParameterDefinitions {

	@ParameterType(".*")
	public Actor actor(String actorName) {
		return OnStage.theActorCalled(actorName);
	}

}
Stedefinitions.java
==============
@Given("{actor} open(s) a browser and launch Web portal")
public void logsWebPortal(Actor actor) {
	actor.wasAbleTo(GoTo.theWebPortalLoginPage());
	actor.wasAbleTo(GoTo.clickLogin());
}

build.gradle:
============
ext {
        logbackVersion = '1.2.3'
	junitVersion = '4.12'
	assertJVersion = '3.8.0'
	
	serenityCoreVersion = '2.3.9'
	cucumberVersion = '6.8.1'
}

dependencies {
	implementation "ch.qos.logback:logback-classic:${logbackVersion}",
			"net.serenity-bdd:serenity-core:${serenityCoreVersion}",
			"net.serenity-bdd:serenity-screenplay:${serenityCoreVersion}",
			"net.serenity-bdd:serenity-screenplay-webdriver:${serenityCoreVersion}",
			"net.serenity-bdd:serenity-screenplay-rest:${serenityCoreVersion}",
			"net.serenity-bdd:serenity-ensure:${serenityCoreVersion}",
			"org.assertj:assertj-core:${assertJVersion}"

	testImplementation "junit:junit:${junitVersion}",
			"net.serenity-bdd:serenity-cucumber6:${serenityCoreVersion}",
			"io.cucumber:cucumber-java:$cucumberVersion",
			"io.cucumber:cucumber-junit:$cucumberVersion"
}

**Comment by kpkalyan** [comment]
@wakaleo - It seems an issue with Serenity-screenplay only. Where as I could run my step definitions if I use {string} alone expression.

Please let me know, if it is an issue with my dependencies in .gradle

**Comment by wakaleo** [comment]
Make sure you have the parameter type definition in your glue code.

**Comment by kpkalyan** [comment]
Yes @wakaleo . I have created this(ParameterDefinitons.java) file under "src/test/java/web/steps".
Also updated my runner file with this glue, My sample runner file is 

import io.cucumber.junit.CucumberOptions;
import net.serenitybdd.cucumber.CucumberWithSerenity;
import org.junit.runner.RunWith;

@RunWith(CucumberWithSerenity.class)
@CucumberOptions(plugin = { "pretty" }, features = "src/test/resources/features", glue="web.steps", tags = "@SmokeTest")
public class CucumberTestSuite {

}

**Comment by kpkalyan** [comment]
One observation is that 
invoking 'Cucumber step definition builder' on '/<project_name'>  process is taking long time and at the end showing that 
"Building (sleeping) OK"

**Comment by wakaleo** [comment]
I don't know anything about the "Building (sleeping) OK" message - I don't think it is related to Serenity. Compare your project with https://github.com/serenity-bdd/serenity-cucumber-starter, where the approach you describe works correctly.

**Comment by kpkalyan** [comment]
Thank you for response @wakaleo . I am comparing my proj with cucumber-starter.

**Comment by kpkalyan** [comment]
@wakaleo  - I found the issue, The starter project is running fine If I run as it is in the GIT Repo.

In my local I tried to change it to "Project -> Properties -> Configure -> Cucumber Project" and tried to run the runner file and now I see the same issue "Undefined Parameter Type{actor}, Please provide Parameter Type {actor}"

Otherwise it is running successfully. Though I couldn't navigate to Stepedfinitions files from .features (Spring Tool Suite 4 IDE)

**Comment by wakaleo** [comment]
Sound's like an IDE issue - if it runs from the command line, it's not related to the Serenity code.

**Comment by kpkalyan** [comment]
Thank you @wakaleo - closing this issue
