### ISSUE TITLE
[Question] Cucumber Alternative of story.timeout.in.secs for JBehave?

### ISSUE THREAD

**Issue by edricklacbayo** [serenity-bdd/serenity-cucumber6#19]
Is there a Cucumber Alternative for story.timeout.in.secs usually found in serenity.properties?

**Comment by wakaleo** [comment]
No, that's a JBehave attribute that doesn't apply for Cucumber

**Comment by edricklacbayo** [comment]
@wakaleo Is there a Cucumber attribute that does the same? Where I can allot a time window for a test to run?
For example a test only allowed for 30 minutes.

**Comment by edricklacbayo** [comment]
And is there a default runtime window for Cucumber, If yes. Can it be overriden?

**Comment by wakaleo** [comment]
The whole concept (a global timeout on all of your tests, no matter how many you have) is a design "feature" built into JBehave. The concept of putting an arbitrary hard-coded limit on the total duration of your test suite does not exist in Cucumber. What problem are you trying to solve?

**Comment by edricklacbayo** [comment]
It's not actually a problem, it's just a technique we used to do back when we were still using JBehave. Based on your last answer we thought that doing it was just nonsense because we can just use implicit wait to stop features for waiting for an element that wouldn't show up. Thank you @wakaleo

**Comment by edricklacbayo** [comment]
I am closing this question now.
