### ISSUE TITLE
Unable to share data between steps

### ISSUE THREAD

**Issue by qatestingravi** [serenity-bdd/serenity-cucumber6#24]
Environment:
serenity.version: 2.3.6
serenity.maven.version: 2.3.6
serenity.cucumber.version: 2.3.6
junit: 4.12

Steps to reproduce:
1. Pull the project from below github url
https://gitlab.com/alltempprojects/tempuiwebjvjunitcucumberserenity.git
2. Run VerifyContactEmailInFooter.feature 

Observe that, Then Verify test name as "VerifyContactEmailInFooterFeature" step is failed due to data is not shared between steps.

Expected:
Then Verify test name as "VerifyContactEmailInFooterFeature" step should be passed 

Actual:
Then Verify test name as "VerifyContactEmailInFooterFeature" step is FAILED with null value

Note1: Used "TestContext" class in common folder to share data between steps 
Note2: For reference see the results in "reports>serenity-reports" folder
Note3: It is working fine, while using with below 2 lines of code. 
Serenity.setSessionVariable("testName").to(name);
String actualName = Serenity.sessionVariableCalled("testName");

![serenity shared data issue](https://user-images.githubusercontent.com/38858602/110280491-e7aa8700-8000-11eb-8e16-c51511bcb20f.png)

**Comment by wakaleo** [comment]
At a quick glance, looks like a usage issue:
- Page Objects are not steps: do not confuse the two (TextContext extends PageObject but uses @Step-annotated methods - that won't work)
- Never use the @Steps annotation for a page object (i.e. loginPage and homePage)
- Always put the @Steps annotation on your Steps libraries (i.e. testContext)
- Use the shared attribute (@Steps(shared=true)) if you want the same step library instance to be reused.
- Annotations only apply to the field that directly follows them, not to multiple fields.

**Comment by qatestingravi** [comment]
Thanks @wakaleo , I made changes as per your comments and its working, Closing the ticket.
