### ISSUE TITLE
Getting "NoStageException: No stage available" error while running from feature file

### ISSUE THREAD

**Issue by qatestingravi** [serenity-bdd/serenity-cucumber6#25]
Environment:
serenity.version: 2.3.6
serenity.maven.version: 2.3.6
serenity.cucumber.version: 2.3.6
junit: 4.12

Steps to reproduce:

1. Pull the project from below github url
https://gitlab.com/alltempprojects/tempuiwebjvjunitcucumberserenity.git
2. Run VerifyLinksUnderMyAccountInFooter.feature from feature file itself

Expected:
Feature should be run successfully with out any errors

Actual:
Getting below error
net.serenitybdd.screenplay.actors.NoStageException: No stage available - it looks like you haven't called the setTheStage() method before calling this one.

Note1: Run got success with out any errors when running from TestRunner file or mvn command

See the snapshot for reference

![serenity feature file issue](https://user-images.githubusercontent.com/38858602/110281867-80420680-8003-11eb-8e0d-fcfd32792f5f.png)

**Comment by DicksengA** [comment]
If you running from intellij using cucumber plugin. You need write your own main class and pass in Serenity's Cucumber Runtime

**Comment by qatestingravi** [comment]
Hi @DicksengA, thanks for the comment, But I am not sure, how to pass main class to serenity cucumber runtime, can you please provide some inputs/steps to do that?

**Comment by wakaleo** [comment]
It depends on the version of IntelliJ, and isn't guaranteed to work. The simplest answer is that you can't run Serenity tests from the feature file in IntelliJ.

**Comment by qatestingravi** [comment]
Thanks @wakaleo for update, closing the ticket
