### ISSUE TITLE
Duplicate features names appearing in overall test results

### ISSUE THREAD

**Issue by gorakshasabnis** [serenity-bdd/serenity-cucumber6#31]
Hi,

Duplicate entries of feature files are coming the overall summary. I tried moving features folder outside resources too; but in that case requirements are showing feature files, but it opens a blank feature page. 
Is there any workaround here ?

PFA screenshots of report, test runner, properties file & resources structure:

<img width="1787" alt="image" src="https://user-images.githubusercontent.com/18349033/123047963-85dd2400-d41b-11eb-9d86-f9f1e827401c.png">

Test Suite runner:
<img width="746" alt="image" src="https://user-images.githubusercontent.com/18349033/123048081-a4dbb600-d41b-11eb-84ac-134d70dd9070.png">

serenity.properties file:
<img width="587" alt="image" src="https://user-images.githubusercontent.com/18349033/123048163-bcb33a00-d41b-11eb-98db-c0817a9dca2e.png">

Folder Structure
<img width="307" alt="image" src="https://user-images.githubusercontent.com/18349033/123048274-dc4a6280-d41b-11eb-914d-901605058d03.png">

Regards,
Goraksha

**Comment by wakaleo** [comment]
Try not putting spaces in the directory name.

**Comment by gorakshasabnis** [comment]
yes it worked. Thanks.
