### ISSUE TITLE
Unable to use non capturing group with {actor}

### ISSUE THREAD

**Issue by gorakshasabnis** [serenity-bdd/serenity-cucumber6#32]
Lets say, I have written a two different scenario line as below
Scenario: number 1
Given Ben opens reports
And he chooses "report type 1"
When he selects filters as ......

Scenario: number 2
Given Lisa opens reports
And she chooses "report type 2"
When she selects rows as ......

In above example, step definition is same for 'When'; hence i m trying to use non capturing group as
@When({actor} selects (?:filters|rows) as)
public void methodName(){
....}

and I have a defined actor paramter as below:
@ParameterType(".*")
    public Actor actor(String actorName) {
        return OnStage.theActorCalled(actorName);
    }

however, using {actor} in the step definition shows that there is no step definition mapped to a scenario line. So tried below:
@When("^(.*) selects (?:filters|rows) as$")
public void methodName(){
....}

After using (.*) instead of {actor}, cucumber shows that the step definition is present but when i run the code it throws me error as -
**io.cucumber.core.exception.CucumberException: Could not convert arguments for step [^(.*) selects (?:filters|rows) as$]**

can you please suggest?

**Comment by wakaleo** [comment]
You can't mix regexes and Cucumber expressions.

**Comment by gorakshasabnis** [comment]
Then how can i use non capturing group with {actor} ?

**Comment by wakaleo** [comment]
You can't, you need to use regexes if you want non-capturing groups so you can't use the {actor} expression in that case.

**Comment by gorakshasabnis** [comment]
if i use (.*) instead of {actor} then i got error as 'io.cucumber.core.exception.CucumberException: Could not convert arguments for step [^(.) selects (?:filters|rows) as$]'

**Comment by wakaleo** [comment]
If you use a regex you cannot have a parameter of type Actor - you need to convert the name of the actor to the actor by hand in the step.

**Comment by gorakshasabnis** [comment]
Understood. It worked after I implemented ur solution. Thank you so much. Appreciate your help. :)
