### ISSUE TITLE
Cut ties with junit4 to allow using cucumber-junit-platform-launcher

### ISSUE THREAD

**Issue by nicerloop** [serenity-bdd/serenity-cucumber6#35]
See https://github.com/serenity-bdd/serenity-cucumber5/pull/3 for starters.

**Comment by wakaleo** [comment]
Sounds reasonable - could you propose a PR?

**Comment by nicerloop** [comment]
Obsoleted by https://github.com/serenity-bdd/serenity-core/pull/2648
